/**
 * ==============================================================================
 * YARDBIRD'S GAMES — CARTRIDGE: FAST MATH  (mathLogic.js)
 * ==============================================================================
 *
 * WHAT THIS GAME IS:
 *   An arcade-style pattern-recognition battle under the clock.
 *   A target number appears at the top of the screen. Four equations are
 *   displayed — only one equals the target. Players must spot it fast using
 *   mental shortcuts: digit parity, elimination, and number sense — not
 *   brute-force arithmetic. Speed is rewarded; hesitation is punished.
 *
 * MODES:
 *   · Addition       — Which equation sums to the target?
 *   · Subtraction    — Spot the right difference.
 *   · Multiplication — Find the equation that hits the product.
 *   · Division       — Which pair divides cleanly to the target?
 *   · Mixed          — All four operators appear simultaneously. Maximum chaos.
 *
 * DIFFICULTY LEVELS:
 *   · Easy         — 20s per round; one wrong option fades at the 10s mark.
 *   · Hard         — 6s per round. Pure reflexes.
 *   · Sudden Death — 10s per round; one wrong answer from ANY player ends the run.
 *
 * SCORING:
 *   · Time-based: faster guesses earn more points.
 *   · Streak Bonus: +50 pts every 3rd consecutive correct answer.
 *   · Double Rounds: every 5th round, points are ×2.
 *   · Sudden Death: score is replaced by rounds-survived counter.
 *
 * MULTIPLAYER:
 *   Fully supports Host (TV) + Client (Phone) Kahoot-style play.
 *   Host broadcasts round state via Firebase. Clients submit MC guesses.
 *   evaluateMultiplayerRound() scores all players simultaneously.
 *   Sudden Death ends the entire room if ANY player answers incorrectly.
 *
 * CARTRIDGE CONTRACT (required by app.js validateCartridge):
 *   ✅ manifest                  — game metadata & setup config
 *   ✅ startGame()               — entry point called by the platform
 *   ✅ nextRound()               — advances to the next problem
 *   ✅ evaluateGuess()           — solo scoring logic
 *   ✅ evaluateMultiplayerRound()— multiplayer scoring logic
 *   ✅ endGameSequence()         — results screen + stat tracking
 *   ✅ handleStop()              — stub (no audio stream to stop)
 *   ✅ forceLifeline()           — stub (no lifeline mechanic in Math)
 *   ✅ startDailyChallenge()     — stub (daily mode not yet implemented)
 *   ✅ resetStats()              — clears localStorage for this cartridge
 *   ✅ shareChallenge()          — platform share sheet integration
 *   ✅ renderStatsUI()           — injects stats HTML into the stats modal
 *
 * PROBLEM GENERATION STRATEGY:
 *   Wrong answers are deliberately deceptive — they share surface features
 *   with the correct equation (same operator, similar-magnitude numbers)
 *   so players cannot trivially eliminate them. Mixed mode assigns each
 *   wrong option a random operator, forcing cross-operator scanning.
 *
 * FILE STRUCTURE (section map):
 *   SECTION 1  — Imports & Module-Level State
 *   SECTION 2  — Manifest (Cartridge Contract)
 *   SECTION 3  — Stats & Sharing
 *   SECTION 4  — Problem Generator: Single Operator
 *   SECTION 5  — Problem Generator: Mixed Operator
 *   SECTION 6  — Problem Generator: Entry Point
 *   SECTION 7  — Game Helpers & UI Utilities
 *   SECTION 8  — startGame()
 *   SECTION 9  — nextRound()
 *   SECTION 10 — evaluateGuess()   (Solo)
 *   SECTION 11 — evaluateMultiplayerRound()   (Multiplayer Host)
 *   SECTION 12 — endGameSequence()
 *   SECTION 13 — Platform Stubs
 * ==============================================================================
 */


// ==============================================================================
// SECTION 1 — IMPORTS & MODULE-LEVEL STATE
// ==============================================================================

import { db } from './firebase.js';
import { state, sfxTick, sfxCheer, sfxBuzzer, colors, bgm } from './state.js';

/**
 * _currentProblem  {Object|null}
 * ─────────────────────────────
 * Holds the problem object generated by generateMathProblem() for the
 * current round. Stored at module level so evaluateGuess() can always
 * reference the live problem without passing it through the DOM.
 *
 * Shape: { target: number, options: Array<{ text, isCorrect }> }
 *
 * Reset to null at the start of every new problem in nextRound().
 */
let _currentProblem = null;


// ==============================================================================
// SECTION 2 — MANIFEST (CARTRIDGE CONTRACT)
// ==============================================================================

/**
 * manifest  {Object}
 * ───────────────────
 * The single source of truth for this cartridge's identity and setup config.
 * app.js reads this object to populate the game-select screen, setup screen,
 * rules modal, and to register this game with the platform engine.
 *
 * REQUIRED FIELDS (enforced by app.js validateCartridge):
 *   id         — Unique string key. Must match the cartridgeRegistry entry in app.js.
 *   title      — Display name shown on the game-select card.
 *   subtitle   — Short tagline shown under the title.
 *   hasDaily   — false = hides the "Today Three" global challenge button.
 *   rulesHTML  — Injected verbatim into #rules-modal when the "?" button is tapped.
 *   modes[]    — Array of mode objects. First entry is the default selection.
 *   levels[]   — Array of level objects. First entry is the default selection.
 *   clientUI   — Tells the phone controller which UI layout to render.
 *                "multiple-choice" = renders the 4-button MC grid on the phone.
 */
export const manifest = {
    id: "fast_math",
    title: "FAST MATH",
    subtitle: "Pattern recognition under pressure",
    hasDaily: false,
    rulesHTML: `
        <h2>How to Play</h2>
        <div style="text-align:left; color:var(--dark-text); line-height:1.7; font-size:0.95rem;">
            <p>A <strong>target number</strong> appears. Four equations are shown — only one equals the target. Spot it fast.</p>
            <p>You don't need to calculate everything. Use digit patterns, parity, and elimination to find the answer instantly.</p>
            <p><strong style="color:var(--primary);">🎲 Mixed Mode:</strong> All four operators appear together. Scan across addition, subtraction, multiplication, and division simultaneously.</p>
            <p><strong style="color:var(--primary);">💀 Sudden Death:</strong> No timer. Unlimited rounds. One wrong answer ends everything.</p>
            <p><strong style="color:var(--primary);">🔥 Streak Bonus:</strong> 3 correct in a row earns +50 bonus points.</p>
        </div>
        <button class="btn btn-main" onclick="hideModal('rules-modal')" style="margin-top:15px; width:100%;">Let's Go!</button>
    `,
    modes: [
        // Mixed is listed first so it is the default selection on the setup screen.
        { id: "mixed",          title: "🎲 Mixed",          desc: "All operators, random order. Maximum chaos." },
        { id: "addition",       title: "➕ Addition",       desc: "Which equation sums to the target?" },
        { id: "subtraction",    title: "➖ Subtraction",    desc: "Spot the right difference." },
        { id: "multiplication", title: "✖️ Multiplication", desc: "Find the equation that hits the product." },
        { id: "division",       title: "➗ Division",       desc: "Which pair divides cleanly to the target?" }
    ],
    levels: [
        // Sudden Death is listed first so it is the default selection on the setup screen.
        { id: "sudden_death", title: "💀 Sudden Death", desc: "10s per round. One wrong answer ends it all." },
        { id: "easy",         title: "🟢 Easy",         desc: "20s per round. One wrong option fades at 10s." },
        { id: "hard",         title: "🔴 Lightning",    desc: "6s per round. Pure reflexes." }
    ],
    clientUI: "multiple-choice"
};


// ==============================================================================
// SECTION 3 — STATS & SHARING
// ==============================================================================

/**
 * resetStats()
 * ─────────────
 * EXPORTED — wired to the "Reset Stats" button in the stats modal.
 * Clears all Fast Math statistics from the platform's shared localStorage key
 * and replaces them with a clean default object.
 *
 * WHY confirm()?
 *   Stats are stored per-cartridge under state.userStats.fast_math.
 *   Resetting is permanent — this guard gives the player one last chance
 *   to back out before nuking their history.
 */
export function resetStats() {
    if (confirm("Reset your Fast Math stats? This cannot be undone.")) {
        state.userStats.fast_math = {
            gamesPlayed: 0,
            highScore: 0,
            bestStreak: 0,
            suddenDeathRecord: 0
        };
        localStorage.setItem('yardbirdPlatformStats', JSON.stringify(state.userStats));
        alert("Fast Math stats reset.");
    }
}

/**
 * renderStatsUI()
 * ────────────────
 * EXPORTED — called by ui.js when the stats modal opens and Fast Math is active.
 * Injects a formatted HTML summary of the player's career stats into #stats-content.
 *
 * READS FROM:  state.userStats.fast_math  (persisted in localStorage)
 * WRITES TO:   document.getElementById('stats-content').innerHTML
 */
export function renderStatsUI() {
    const s = state.userStats.fast_math || {};
    document.getElementById('stats-content').innerHTML = `
        <div style="display:grid; grid-template-columns:1fr 1fr; gap:12px; text-align:center; margin-bottom:20px;">
            <div class="stat-box"><div class="stat-num">${s.gamesPlayed  || 0}</div><div class="stat-lbl">Games Played</div></div>
            <div class="stat-box"><div class="stat-num">${s.highScore    || 0}</div><div class="stat-lbl">High Score</div></div>
            <div class="stat-box"><div class="stat-num">${s.bestStreak   || 0}</div><div class="stat-lbl">Best Streak</div></div>
            <div class="stat-box"><div class="stat-num">${s.suddenDeathRecord || 0}</div><div class="stat-lbl">💀 SD Record</div></div>
        </div>`;
}

/**
 * shareChallenge()
 * ─────────────────
 * EXPORTED — wired to the "Share" button on the finale screen.
 * Uses the Web Share API when available (mobile); falls back to clipboard copy.
 *
 * BRANCHING:
 *   · Sudden Death  → shares rounds-survived count via state.sdRoundsAlive.
 *   · Standard mode → shares final score from state.rawScores[0].
 *
 * WHY window.location?
 *   Produces the canonical game URL so friends can tap directly into the game.
 */
export function shareChallenge() {
    const score    = state.rawScores[0] || 0;
    const modeName = state.gameState.mode?.replace('_', ' ').toUpperCase() || 'MATH';
    const text     = isSuddenDeath()
        ? `💀 Yardbird Fast Math - Sudden Death\nI survived ${state.sdRoundsAlive || 0} rounds in ${modeName} mode!\nCan you beat me?`
        : `➕ Yardbird Fast Math\nI scored ${score} pts in ${modeName} mode!\nThink you're faster?`;

    const url = `${window.location.origin}${window.location.pathname}`;
    if (navigator.share) {
        navigator.share({ title: "Beat My Math Score!", text, url }).catch(console.error);
    } else {
        navigator.clipboard.writeText(text + "\n" + url);
        alert("Challenge link copied to clipboard!");
    }
}


// ==============================================================================
// SECTION 4 — PROBLEM GENERATOR: SINGLE OPERATOR
// ==============================================================================

/**
 * makeCorrectEquation(op, target)
 * ────────────────────────────────
 * PRIVATE — builds ONE correct equation object for the given operator and target.
 *
 * Design principle: operands are chosen with light randomisation so that the
 * correct answer doesn't always "look" the same (e.g. multiplication always
 * using the smallest factor pair). This prevents players from learning visual
 * shortcuts that bypass number sense.
 *
 * Division note: we construct it backwards — pick a random divisor (b), then
 * derive the dividend (a = target × b) — guaranteeing clean integer division.
 *
 * @param  {string} op     — One of: 'addition' | 'subtraction' | 'multiplication' | 'division'
 * @param  {number} target — The round's target number
 * @returns {Object}       — { a: number, b: number, sym: string }
 */
function makeCorrectEquation(op, target) {
    if (op === 'addition') {
        const a = Math.floor(Math.random() * (target - 2)) + 1;
        return { a, b: target - a, sym: '+' };
    }
    if (op === 'subtraction') {
        const b = Math.floor(Math.random() * Math.max(1, target - 1)) + 1;
        return { a: target + b, b, sym: '−' };
    }
    if (op === 'multiplication') {
        // Gather all valid factor pairs so any pair is equally likely to appear.
        const factors = [];
        for (let i = 2; i <= Math.sqrt(target); i++) {
            if (target % i === 0) factors.push([i, target / i]);
        }
        // Fallback: 1 × target when the target is prime.
        if (factors.length === 0) return { a: 1, b: target, sym: '×' };
        const pair = factors[Math.floor(Math.random() * factors.length)];
        return { a: pair[0], b: pair[1], sym: '×' };
    }
    if (op === 'division') {
        const b = Math.floor(Math.random() * 10) + 2;  // Divisor between 2–11
        return { a: target * b, b, sym: '÷' };
    }
}

/**
 * makeWrongEquations(op, target, correctEq, count)
 * ─────────────────────────────────────────────────
 * PRIVATE — generates `count` deceptive wrong equations for single-operator mode.
 *
 * KEY INSIGHT:
 *   Wrong answers intentionally share surface features with the correct one:
 *   same operator, operands of similar magnitude. This forces players to
 *   actually evaluate — they cannot eliminate wrong answers by type or size alone.
 *
 *   The seen-set ensures no equation pair repeats, and the result is checked
 *   against `target` so no wrong answer accidentally equals the target.
 *
 * SAFETY VALVE:
 *   The 200-attempt ceiling prevents an infinite loop on edge cases (e.g.
 *   a prime target with very few valid operand combinations).
 *
 * @param  {string} op         — Operator used in this round
 * @param  {number} target     — Round's target number (wrong answers must NOT equal this)
 * @param  {Object} correctEq  — The correct equation (used to derive similar operands)
 * @param  {number} count      — Number of wrong equations to generate
 * @returns {Array<Object>}    — Array of { a, b, sym } objects, each != target
 */
function makeWrongEquations(op, target, correctEq, count) {
    const wrongs  = [];
    const seen    = new Set([`${correctEq.a}${correctEq.b}`]);
    let attempts  = 0;

    while (wrongs.length < count && attempts < 200) {
        attempts++;
        let a, b, result;

        if (op === 'addition') {
            // Offset one or both operands by a small delta to stay close to the correct answer.
            const delta = (Math.floor(Math.random() * 4) + 1) * (Math.random() > 0.5 ? 1 : -1);
            a = Math.max(1, correctEq.a + delta);
            b = Math.max(1, correctEq.b + (Math.random() > 0.5 ? delta : -delta));
            result = a + b;

        } else if (op === 'subtraction') {
            const delta = (Math.floor(Math.random() * 5) + 1) * (Math.random() > 0.5 ? 1 : -1);
            a = Math.max(correctEq.b + 2, correctEq.a + delta);  // Keep a > b to avoid negative results
            b = Math.max(1, correctEq.b + (Math.random() > 0.5 ? 1 : -1));
            result = a - b;

        } else if (op === 'multiplication') {
            // Nudge one factor by ±1 or ±2 — keeps numbers visually similar.
            const d = Math.floor(Math.random() * 2) + 1;
            a = Math.max(2, correctEq.a + (Math.random() > 0.5 ? d : -d));
            b = correctEq.b;
            result = a * b;

        } else if (op === 'division') {
            // Change the dividend slightly — same divisor makes it look plausible.
            const d = (Math.floor(Math.random() * 3) + 1) * correctEq.b;
            a = correctEq.a + (Math.random() > 0.5 ? d : -d);
            b = correctEq.b;
            a = Math.max(b + 1, a);  // Ensure dividend > divisor
            result = a / b;
        }

        const key = `${a}${b}`;
        if (seen.has(key) || result === target) continue;
        seen.add(key);

        const symMap = { addition: '+', subtraction: '−', multiplication: '×', division: '÷' };
        wrongs.push({ a, b, sym: symMap[op] });
    }

    return wrongs;
}

/**
 * generateSingleOpProblem(op)
 * ────────────────────────────
 * PRIVATE — assembles a full problem object for a single operator mode.
 *
 * Target ranges per operator:
 *   · Addition / Subtraction  — 10 to 99  (mental arithmetic range)
 *   · Multiplication          — 12 to 144 (times-tables territory)
 *   · Division                — 2 to 12   (small clean quotients)
 *
 * Returns a shuffled options array so the correct answer is never predictably
 * in the same slot each round.
 *
 * @param  {string} op  — Operator for this problem
 * @returns {Object}    — { target: number, options: Array<{text, isCorrect}> }
 */
function generateSingleOpProblem(op) {
    let target;
    if (op === 'addition' || op === 'subtraction') {
        target = Math.floor(Math.random() * 90) + 10;   // 10–99
    } else if (op === 'multiplication') {
        target = Math.floor(Math.random() * 133) + 12;  // 12–144
    } else {
        target = Math.floor(Math.random() * 11) + 2;    // 2–12
    }

    const correctEq    = makeCorrectEquation(op, target);
    const wrongEqs     = makeWrongEquations(op, target, correctEq, 3);

    const correctOption = { text: `${correctEq.a} ${correctEq.sym} ${correctEq.b}`, isCorrect: true };
    const wrongOptions  = wrongEqs.map(eq => ({ text: `${eq.a} ${eq.sym} ${eq.b}`, isCorrect: false }));

    return {
        target,
        options: [correctOption, ...wrongOptions].sort(() => 0.5 - Math.random())
    };
}


// ==============================================================================
// SECTION 5 — PROBLEM GENERATOR: MIXED OPERATOR
// ==============================================================================

/**
 * generateMixedProblem()
 * ───────────────────────
 * PRIVATE — generates a 4-option problem where EACH option uses a DIFFERENT
 * operator. Exactly one evaluates to the target; the other three do not.
 *
 * WHY MIXED IS HARDER:
 *   In single-op mode, players develop one mental strategy (e.g. look for the
 *   right sum). In mixed, every option requires a different cognitive operation.
 *   Players must pattern-switch between addition, subtraction, multiplication,
 *   and division in a single glance.
 *
 * ALGORITHM:
 *   1. Pick a random target in the 10–50 range (smaller = faster to evaluate).
 *   2. Shuffle the four operators.
 *   3. One operator is designated "correct" — build a valid equation for it.
 *   4. The other three operators each get a wrong equation that does NOT
 *      evaluate to the target (loop-guarded with up to 50 attempts each).
 *
 * @returns {Object} — { target: number, options: Array<{text, isCorrect}> }
 */
function generateMixedProblem() {
    const ops      = ['addition', 'subtraction', 'multiplication', 'division'];
    const symMap   = { addition: '+', subtraction: '−', multiplication: '×', division: '÷' };
    const target   = Math.floor(Math.random() * 41) + 10; // 10–50

    // Shuffle operator order so the correct slot is unpredictable.
    const shuffled     = ops.sort(() => 0.5 - Math.random());
    const correctOp    = shuffled[0];
    const correctEq    = makeCorrectEquation(correctOp, target);

    const options = [{
        text: `${correctEq.a} ${symMap[correctOp]} ${correctEq.b}`,
        isCorrect: true
    }];

    // Build one wrong equation per remaining operator.
    for (let i = 1; i < 4; i++) {
        const op = shuffled[i];
        let a, b, result;
        let attempts = 0;

        do {
            attempts++;
            if (op === 'addition') {
                a = Math.floor(Math.random() * 40) + 1;
                b = Math.floor(Math.random() * 40) + 1;
                result = a + b;
            } else if (op === 'subtraction') {
                a = Math.floor(Math.random() * 50) + 11;
                b = Math.floor(Math.random() * 10)  + 1;
                result = a - b;
            } else if (op === 'multiplication') {
                a = Math.floor(Math.random() * 10) + 2;
                b = Math.floor(Math.random() * 10) + 2;
                result = a * b;
            } else {
                b = Math.floor(Math.random() * 9)  + 2;
                a = b * (Math.floor(Math.random() * 10) + 2);
                result = a / b;
            }
        } while (result === target && attempts < 50);

        options.push({ text: `${a} ${symMap[op]} ${b}`, isCorrect: false });
    }

    return {
        target,
        options: options.sort(() => 0.5 - Math.random())
    };
}


// ==============================================================================
// SECTION 6 — PROBLEM GENERATOR: ENTRY POINT
// ==============================================================================

/**
 * generateMathProblem()
 * ──────────────────────
 * PRIVATE — unified entry point that routes to the appropriate generator
 * based on the player's chosen mode in state.gameState.mode.
 *
 * Called by nextRound() once per round.
 *
 * @returns {Object} — { target, options } — see generateSingleOpProblem for shape
 */
function generateMathProblem() {
    if (state.gameState.mode === 'mixed') return generateMixedProblem();
    return generateSingleOpProblem(state.gameState.mode);
}


// ==============================================================================
// SECTION 7 — GAME HELPERS & UI UTILITIES
// ==============================================================================

/**
 * isSuddenDeath()
 * ────────────────
 * PRIVATE — convenience predicate used throughout this file to gate
 * Sudden Death-specific behaviour (different round tag, end condition, sharing text).
 *
 * @returns {boolean}
 */
const isSuddenDeath = () => state.gameState.level === 'sudden_death';

/**
 * _buildScoreBoard()
 * ───────────────────
 * PRIVATE — generates the HTML string for the score pill(s) in the play screen.
 *
 * Solo:        Renders a single pill using colors[0].
 * Multiplayer: Renders one pill per player in the lobby, sorted by player order.
 *
 * The score pill shows: player name · current score · streak indicator.
 * The streak badge is hidden (opacity:0) when streak is 0 to preserve layout.
 *
 * @returns {string} — HTML string injected into #score-board
 */
function _buildScoreBoard() {
    if (!state.isMultiplayer) {
        return `
            <div class="score-pill" style="border-color:${colors[0]};">
                <div class="p-name"   style="color:${colors[0]}">SCORE</div>
                <div class="p-pts"    style="color:var(--dark-text)">${state.rawScores[0] || 0}</div>
                <div class="p-streak" style="opacity:${state.streaks[0] > 0 ? 1 : 0}">🔥 ${state.streaks[0]}</div>
            </div>`;
    }
    // Multiplayer: one pill per player
    return state.playerNames.map((name, i) => `
        <div class="score-pill" style="border-color:${colors[i]};">
            <div class="p-name"   style="color:${colors[i]}">${name}</div>
            <div class="p-pts"    style="color:var(--dark-text)">${state.rawScores[i] || 0}</div>
            <div class="p-streak" style="opacity:${(state.streaks[i] || 0) > 0 ? 1 : 0}">🔥 ${state.streaks[i] || 0}</div>
        </div>`).join('');
}

/**
 * _renderMCButtons(options)
 * ──────────────────────────
 * PRIVATE — injects 4 multiple-choice buttons into #mc-fields for the current round.
 *
 * Each button's onclick passes two arguments to the platform bridge:
 *   · opt.isCorrect  — grading signal for evaluateGuess()
 *   · this           — the DOM element, so evaluateGuess can colour it red/green
 *
 * WHY pass `this`?
 *   The platform needs to highlight the clicked button immediately without
 *   searching the DOM for which one was tapped. Passing the element directly
 *   is faster and eliminates a querySelector call.
 *
 * @param {Array<{text: string, isCorrect: boolean}>} options — The 4 answer choices
 */
function _renderMCButtons(options) {
    const container = document.getElementById('mc-fields');
    container.classList.remove('hidden');
    container.innerHTML = options.map(opt => `
        <button class="mc-btn" onclick="evaluateGuess(${opt.isCorrect}, this)">
            ${opt.text}
        </button>`).join('');
}

/**
 * _startRoundTimer(timeLimit, onExpire)
 * ──────────────────────────────────────
 * PRIVATE — starts the countdown timer for the current round.
 *
 * Each tick:
 *   · Updates the #timer-display element.
 *   · At the halfway point (Easy only): fades one wrong button to give a hint.
 *   · Plays sfxTick for urgency in the last 3 seconds.
 *   · At 0: clears itself and calls onExpire() (evaluates as incorrect).
 *
 * The timer ID is stored in state.timerId so it can be cancelled by
 * evaluateGuess() or evaluateMultiplayerRound() when the player answers
 * before time runs out.
 *
 * @param {number}   timeLimit — Seconds for this round (set by difficulty level)
 * @param {Function} onExpire  — Callback invoked when the timer hits 0
 */
function _startRoundTimer(timeLimit, onExpire) {
    let timeLeft = timeLimit;
    const display = document.getElementById('timer-display');
    if (display) display.innerText = timeLeft;

    state.timerId = setInterval(() => {
        timeLeft--;
        if (display) display.innerText = timeLeft;

        // Auditory urgency cue in the last 3 seconds
        if (timeLeft <= 3 && timeLeft > 0) {
            sfxTick.currentTime = 0;
            sfxTick.play().catch(() => {});
        }

        // Easy-mode hint: fade one wrong button at the halfway point
        if (state.gameState.level === 'easy' && timeLeft === Math.floor(timeLimit / 2)) {
            const wrongBtns = [...document.querySelectorAll('#mc-fields .mc-btn')]
                .filter(btn => !btn.onclick.toString().includes('true'));
            if (wrongBtns.length > 0) {
                wrongBtns[Math.floor(Math.random() * wrongBtns.length)].style.opacity = '0.2';
            }
        }

        if (timeLeft <= 0) {
            clearInterval(state.timerId);
            onExpire();
        }
    }, 1000);
}


// ==============================================================================
// SECTION 8 — startGame()
// ==============================================================================

/**
 * startGame()
 * ────────────
 * EXPORTED — the platform's entry point into this cartridge.
 * Called by app.js when the player taps "Start Game" or "Start Multiplayer".
 *
 * RESPONSIBILITIES:
 *   1. Garbage-collect state left by other cartridges (songs, pool, matchHistory).
 *   2. Set time limits based on chosen difficulty level.
 *   3. Generate double-round indices (every 5 rounds, one round is ×2 score).
 *   4. Initialize score and streak arrays for solo or multiplayer player count.
 *   5. Transition the UI from setup-screen → play-screen.
 *   6. Kick off the first round via nextRound().
 *
 * DOUBLE ROUND LOGIC:
 *   For every block of 5 rounds, exactly one random round is flagged as a
 *   double-point round. This gives players a surprise score boost mid-game
 *   without being predictable. Sudden Death skips this since score is irrelevant.
 *
 * SUDDEN DEATH NOTE:
 *   sdRoundsAlive is the primary stat tracked during Sudden Death play.
 *   It replaces the traditional score as the metric displayed on the finale.
 */
export function startGame() {
    // ── Garbage collection: wipe state from other cartridges ──
    state.curIdx       = 0;
    state.songs        = [];
    state.globalPool   = [];
    state.matchHistory = [];
    state.isDailyMode  = false;
    state.numPlayers   = state.isMultiplayer ? state.numPlayers : 1;

    // ── Time limit per difficulty level ──
    if      (state.gameState.level === 'easy')   state.timeLimit = 20;
    else if (state.gameState.level === 'medium') state.timeLimit = 12;
    else if (state.gameState.level === 'hard')   state.timeLimit = 6;
    else                                         state.timeLimit = 10; // Sudden Death

    state.maxRounds    = state.gameState.rounds;
    state.sdRoundsAlive = 0;

    // ── Double-round generation (skip for Sudden Death) ──
    state.doubleRounds = [];
    if (!isSuddenDeath()) {
        for (let i = 0; i < state.maxRounds; i += 5) {
            const min = i === 0 ? 2 : i;
            const max = Math.min(i + 4, state.maxRounds - 1);
            if (min <= max) {
                state.doubleRounds.push(Math.floor(Math.random() * (max - min + 1)) + min);
            }
        }
    }

    // ── Initialize per-player score and streak arrays ──
    state.curIdx    = 0;
    state.rawScores = new Array(state.numPlayers).fill(0);
    state.streaks   = new Array(state.numPlayers).fill(0);

    // ── UI transition: setup → play ──
    document.getElementById('setup-screen').classList.add('hidden');
    document.getElementById('play-screen').classList.remove('hidden');
    document.querySelectorAll('.header-btn').forEach(btn => btn.classList.add('hidden'));

    // Hide elements that belong to Song Trivia
    document.getElementById('guess-fields').classList.add('hidden');
    document.getElementById('btn-container').classList.add('hidden');
    document.getElementById('visualizer').classList.add('hidden');
    document.getElementById('reveal-art').style.display = 'none';

    // Solo: render a blank score pill ready to be updated each round.
    if (!state.isHost) {
        document.getElementById('score-board').innerHTML = `
            <div class="score-pill" style="border-color:${colors[0]};">
                <div class="p-name"   style="color:${colors[0]}">SCORE</div>
                <div class="p-pts"    style="color:var(--dark-text)">0</div>
                <div class="p-streak" style="opacity:0">🔥 0</div>
            </div>`;
    }

    nextRound();
}


// ==============================================================================
// SECTION 9 — nextRound()
// ==============================================================================

/**
 * nextRound()
 * ────────────
 * EXPORTED — advances the game to the next round or ends the game if all
 * rounds are exhausted. Called by startGame() for round 0, then by
 * evaluateGuess() / evaluateMultiplayerRound() after a 2-second feedback pause.
 *
 * FLOW:
 *   1. Check if the game is over (curIdx >= maxRounds). If so → endGameSequence().
 *   2. Reset isProcessing so the next answer can register.
 *   3. Generate a fresh math problem via generateMathProblem().
 *   4. Update the round tag (#active-player) with round number or SD counter.
 *   5. Display the target number in the designated element.
 *   6. Render 4 MC buttons via _renderMCButtons().
 *   7. Start the countdown timer via _startRoundTimer().
 *
 * SUDDEN DEATH TIMER EXPIRY:
 *   When the timer hits 0 in Sudden Death, it calls evaluateGuess(false)
 *   to trigger the death sequence — same path as a wrong button tap.
 *
 * MULTIPLAYER NOTE:
 *   In multiplayer, nextRound() only runs on the HOST. Clients receive round
 *   state via Firebase and update their phone UI through the multiplayer listener.
 */
export function nextRound() {
    if (state.curIdx >= state.maxRounds) { endGameSequence(); return; }

    state.isProcessing  = false;
    _currentProblem     = generateMathProblem();
    state.currentCorrectAnswer = _currentProblem.target;

    const tag      = document.getElementById('active-player');
    const isDouble = !isSuddenDeath() && state.doubleRounds.includes(state.curIdx);

    // ── Round tag (top badge above the equation) ──
    if (isSuddenDeath()) {
        tag.innerText     = `💀 SUDDEN DEATH — Round ${state.sdRoundsAlive + 1}`;
        tag.style.color   = 'var(--fail)';
        tag.style.borderColor = 'var(--fail)';
    } else {
        tag.innerText     = `ROUND ${state.curIdx + 1}/${state.maxRounds}${isDouble ? ' — ⭐ 2X BONUS' : ''}`;
        tag.style.color   = isDouble ? '#f39c12' : 'var(--primary)';
        tag.style.borderColor = isDouble ? '#f39c12' : 'var(--primary)';
    }

    // ── Display the target number ──
    const targetEl = document.getElementById('math-target');
    if (targetEl) targetEl.innerText = _currentProblem.target;

    // ── Clear feedback from previous round ──
    const feedback = document.getElementById('feedback');
    if (feedback) feedback.innerHTML = '';

    // ── Render the four answer buttons ──
    _renderMCButtons(_currentProblem.options);

    // ── Start the countdown ──
    _startRoundTimer(state.timeLimit, () => {
        // Timer expired: treat as a wrong answer
        evaluateGuess(false, null);
    });

    // ── Sync to Firebase for multiplayer clients ──
    if (state.isMultiplayer && state.isHost) {
        db.ref(`rooms/${state.roomCode}/currentRound`).set({
            round:   state.curIdx,
            target:  _currentProblem.target,
            options: _currentProblem.options,
            isDouble
        });
    }
}


// ==============================================================================
// SECTION 10 — evaluateGuess() — SOLO
// ==============================================================================

/**
 * evaluateGuess(isCorrect, clickedBtn)
 * ──────────────────────────────────────
 * EXPORTED — called by app.js window.evaluateGuess() delegation.
 * Handles solo scoring only. evaluateMultiplayerRound() handles host scoring.
 *
 * FLOW:
 *   1. Guard against double-evaluation (state.isProcessing flag).
 *   2. Stop the timer immediately.
 *   3. Stop background music (if any was playing).
 *   4. Disable all MC buttons to prevent further input.
 *   5. Colour the clicked button: red if wrong, green if correct.
 *   6. Calculate points (time-based + streak bonus + double-round multiplier).
 *   7. Handle Sudden Death elimination if wrong.
 *   8. Update #feedback and #score-board.
 *   9. Advance to next round after a 2s pause.
 *
 * SCORING FORMULA (standard modes):
 *   basePoints = timeRemaining / timeLimit × 200   (max ~200 per round)
 *   streakBonus = +50 every 3rd consecutive correct
 *   doubleRound = total × 2
 *
 * SUDDEN DEATH:
 *   A wrong answer triggers endGameSequence() directly.
 *   sdRoundsAlive is the persistent stat (not rawScores).
 *
 * @param {boolean}          isCorrect  — Whether the tapped button was correct
 * @param {HTMLElement|null} clickedBtn — The button the player tapped (for colouring)
 */
export function evaluateGuess(isCorrect, clickedBtn = null) {
    // ── Guard: prevent double-fire from rapid taps or timer+button race ──
    if (state.isProcessing) return;
    state.isProcessing = true;

    clearInterval(state.timerId);
    bgm.pause();
    bgm.currentTime = 0;

    // ── Disable all buttons to lock input ──
    document.querySelectorAll('#mc-fields .mc-btn').forEach(b => { b.disabled = true; });

    // ── Visual feedback on the clicked button ──
    if (clickedBtn) clickedBtn.classList.add(isCorrect ? 'correct' : 'wrong');

    // ── Reveal the correct button (green) so players see it after wrong answers ──
    document.querySelectorAll('#mc-fields .mc-btn').forEach(btn => {
        if (btn.onclick?.toString().includes('true')) btn.classList.add('correct');
    });

    const isDouble  = !isSuddenDeath() && state.doubleRounds.includes(state.curIdx);
    const feedback  = document.getElementById('feedback');
    let   roundPts  = 0;

    if (isCorrect) {
        state.streaks[0]++;
        state.sdRoundsAlive++;

        // Time-based scoring: reward speed relative to the time limit
        const timerEl   = document.getElementById('timer-display');
        const timeLeft  = parseInt(timerEl?.innerText || 0, 10);
        roundPts        = Math.round(100 + (timeLeft / state.timeLimit) * 100);

        const streakBonus = (state.streaks[0] > 0 && state.streaks[0] % 3 === 0);
        if (streakBonus) roundPts += 50;
        if (isDouble)    roundPts  = Math.round(roundPts * 2);

        state.rawScores[0] += roundPts;
        sfxCheer.currentTime = 0; sfxCheer.play().catch(() => {});

        const streakMsg = streakBonus
            ? `<div style="color:var(--p3); font-size:0.9rem; margin-top:4px; font-weight:bold;">🔥 ${state.streaks[0]}-streak! +50 bonus</div>`
            : '';
        const doubleMsg = isDouble
            ? `<div style="color:#f39c12; font-size:0.9rem; font-weight:bold; margin-top:4px;">⭐ 2X BONUS ROUND!</div>`
            : '';

        if (feedback) feedback.innerHTML = `
            <div style="color:var(--success); font-size:1.4rem; font-weight:bold; margin-top:10px;">
                ✅ CORRECT! +${roundPts}
            </div>${streakMsg}${doubleMsg}`;

    } else {
        state.streaks[0] = 0;
        sfxBuzzer.currentTime = 0; sfxBuzzer.play().catch(() => {});

        if (isSuddenDeath()) {
            // ── Sudden Death: wrong answer = game over ──
            if (feedback) feedback.innerHTML = `
                <div style="color:var(--fail); font-size:2rem; font-weight:900; margin-top:15px;">💀 ELIMINATED!</div>
                <div style="color:var(--fail); font-size:1.1rem; margin-top:5px;">You survived ${state.sdRoundsAlive} rounds.</div>`;
            setTimeout(endGameSequence, 2500);
            return; // Skip the normal advance
        }

        if (feedback) feedback.innerHTML = `
            <div style="color:var(--fail); font-size:1.4rem; font-weight:bold; margin-top:10px;">
                ❌ INCORRECT
            </div>`;
    }

    // ── Update the score pill ──
    document.getElementById('score-board').innerHTML = _buildScoreBoard();

    // ── Advance after 2s feedback window ──
    state.curIdx++;
    setTimeout(nextRound, 2000);
}


// ==============================================================================
// SECTION 11 — evaluateMultiplayerRound() — MULTIPLAYER HOST
// ==============================================================================

/**
 * evaluateMultiplayerRound(players)
 * ───────────────────────────────────
 * EXPORTED — called by app.js window.evaluateMultiplayerRound() delegation.
 * Scores ALL connected players simultaneously based on their Firebase guesses.
 *
 * CALLED BY:
 *   · multiplayer.js startMultiplayerGame() → players listener (all locked)
 *   · _startRoundTimer() onExpire callback  → time's up (host only)
 *
 * SCORING LOGIC:
 *   · Correct MC guess → 100 + (time × 100 / timeLimit) pts  (speed-weighted)
 *   · Wrong/no guess   → 0 points
 *   · Streak bonus     → +50 every 3rd consecutive correct
 *   · Double round     → total × 2
 *
 * SUDDEN DEATH (multiplayer):
 *   ANY player getting it wrong ends the room. The host writes 'gameover'
 *   to Firebase, then calls endGameSequence() after a 4s dramatic pause.
 *   finalizeMultiplayerRound() is still called first so score writes complete.
 *
 * FIREBASE WRITES (delegated to finalizeMultiplayerRound):
 *   · Updates each player's score in /rooms/{code}/players/{id}/score
 *   · Advances currentRound so phones know a new round started
 *   · Clears currentMC so phones drop the old buttons
 *
 * @param {Object} players — Firebase snapshot value: { playerId: { name, guess, score } }
 */
export async function evaluateMultiplayerRound(players) {
    if (state.isProcessing) return;
    state.isProcessing = true;
    if (state.timerId) clearInterval(state.timerId);

    bgm.pause();
    bgm.currentTime = 0;

    const results  = [];
    const isDouble = !isSuddenDeath() && state.doubleRounds.includes(state.curIdx);
    let fbHTML     = `<div style="display:flex; flex-direction:column; gap:6px; margin-bottom:15px; font-weight:bold;">`;

    let fatalMistake = false;
    let guiltyPlayer = "";

    Object.keys(players).forEach((pid, index) => {
        const p       = players[pid];
        const correct = !!(p.guess && p.guess.isMC && p.guess.correct);
        let   roundPts = 0;

        if (correct) {
            state.streaks[index] = (state.streaks[index] || 0) + 1;

            // Speed factor: how quickly did they answer relative to the time limit?
            const speedFactor = (p.guess.time || 0) / state.timeLimit;
            roundPts = Math.round(100 + (speedFactor * 100));

            const streakBonus = (state.streaks[index] > 0 && state.streaks[index] % 3 === 0);
            if (streakBonus) roundPts += 50;
            if (isDouble)    roundPts *= 2;

            fbHTML += `<div style="color:var(--success); font-size:1.1rem;">✅ ${p.name}: +${roundPts}</div>`;
            state.rawScores[index] = (state.rawScores[index] || 0) + roundPts;
        } else {
            state.streaks[index] = 0;
            fbHTML += `<div style="color:var(--fail); font-size:1.1rem;">❌ ${p.name}: 0</div>`;

            // In Sudden Death, any wrong answer kills the room
            if (isSuddenDeath()) {
                fatalMistake = true;
                guiltyPlayer = p.name;
            }
        }

        results.push({ id: pid, newScore: (p.score || 0) + roundPts });
    });

    fbHTML += `</div>`;

    if (fatalMistake) {
        // ── Sudden Death: room eliminated ──
        document.getElementById('feedback').innerHTML = fbHTML + `
            <div style="color:var(--fail); font-size:2rem; font-weight:900; margin-top:15px; line-height:1;">💀 FATAL MISTAKE!</div>
            <div style="color:var(--fail); font-size:1.2rem; margin-top:5px;"><strong>${guiltyPlayer}</strong> eliminated the room!</div>`;

        if (window.finalizeMultiplayerRound) window.finalizeMultiplayerRound(results);
        setTimeout(endGameSequence, 4000);
        return; // Prevent nextRound from firing
    }

    // ── Standard round: show results and advance ──
    document.getElementById('feedback').innerHTML = fbHTML;
    document.getElementById('score-board').innerHTML = _buildScoreBoard();

    state.curIdx++;
    if (window.finalizeMultiplayerRound) window.finalizeMultiplayerRound(results);
    setTimeout(nextRound, 2000);
}


// ==============================================================================
// SECTION 12 — endGameSequence()
// ==============================================================================

/**
 * endGameSequence()
 * ──────────────────
 * PRIVATE — called when all rounds are complete (or Sudden Death eliminates players).
 * Transitions the play-screen → final-screen and writes final stat updates.
 *
 * STAT TRACKING:
 *   · Increments gamesPlayed on every run.
 *   · Updates highScore if the current score beats the record.
 *   · Updates bestStreak from state.streaks[0].
 *   · Updates suddenDeathRecord (rounds survived) only in Sudden Death mode.
 *
 * MULTIPLAYER:
 *   · Host writes phase: 'gameover' to Firebase, triggering client finale screens.
 *   · Reads the final leaderboard from Firebase to build the podium.
 *
 * SOLO FINALE HTML:
 *   Renders a gradient score card with mode, score, and a new-record badge if earned.
 */
function endGameSequence() {
    clearInterval(state.timerId);
    bgm.pause();
    bgm.currentTime = 0;

    document.getElementById('play-screen').classList.add('hidden');
    document.getElementById('final-screen').classList.remove('hidden');
    document.getElementById('final-subtitle').innerText = isSuddenDeath()
        ? "💀 Sudden Death — Rounds Survived"
        : "Speed + Accuracy Scoring";

    // ── Stat persistence ──
    const s = state.userStats.fast_math || {};
    s.gamesPlayed = (s.gamesPlayed || 0) + 1;

    const finalScore = state.rawScores[0] || 0;
    const newRecord  = finalScore > (s.highScore || 0);
    if (newRecord) s.highScore = finalScore;

    const finalStreak = state.streaks[0] || 0;
    if (finalStreak > (s.bestStreak || 0)) s.bestStreak = finalStreak;

    if (isSuddenDeath() && (state.sdRoundsAlive || 0) > (s.suddenDeathRecord || 0)) {
        s.suddenDeathRecord = state.sdRoundsAlive;
    }

    state.userStats.fast_math = s;
    localStorage.setItem('yardbirdPlatformStats', JSON.stringify(state.userStats));

    // ── Multiplayer finale (host only) ──
    if (state.isMultiplayer && state.isHost) {
        db.ref(`rooms/${state.roomCode}/hostState`).set({ phase: 'gameover' });

        db.ref(`rooms/${state.roomCode}/players`).once('value', snap => {
            const players = snap.val() || {};
            const results = Object.keys(players)
                .map(pid => ({ name: players[pid].name, score: players[pid].score || 0 }))
                .sort((a, b) => b.score - a.score);

            db.ref(`rooms/${state.roomCode}/finalLeaderboard`).set(results);

            let podium = `<div style="text-align:left; background:var(--surface); padding:15px; border-radius:12px; border:2px solid var(--border-light);">`;
            results.forEach((p, i) => {
                const medal = ['🥇', '🥈', '🥉'][i] || '👏';
                podium += `<div style="padding:6px 0; font-size:1.1rem; font-weight:bold;">
                    ${medal} ${p.name} — <span style="color:var(--primary)">${p.score} pts</span>
                </div>`;
            });
            podium += `</div>`;
            document.getElementById('winner-text').innerHTML = podium;
        });
        return;
    }

    // ── Solo finale ──
    const sdLine = isSuddenDeath()
        ? `<div style="font-size:1rem; color:var(--fail); margin-top:8px;">💀 Survived: ${state.sdRoundsAlive} rounds</div>`
        : '';
    const recordLine = newRecord
        ? `<div style="color:#f39c12; font-size:0.9rem; margin-top:6px; font-weight:bold;">🏆 NEW HIGH SCORE!</div>`
        : '';

    document.getElementById('winner-text').innerHTML = `
        <div style="background:linear-gradient(135deg, var(--primary), var(--p2)); border-radius:16px; padding:20px; color:#fff;">
            <div style="font-size:2.2rem; font-weight:900;">${finalScore}</div>
            <div style="font-size:0.9rem; opacity:0.85; text-transform:uppercase; letter-spacing:1px;">
                ${state.gameState.mode?.replace('_', ' ')} · ${state.gameState.level?.replace('_', ' ')}
            </div>
            ${sdLine}${recordLine}
        </div>`;
}


// ==============================================================================
// SECTION 13 — PLATFORM STUBS
// ==============================================================================

/**
 * The following functions are required by app.js validateCartridge() to satisfy
 * the Cartridge Contract, but Fast Math does not use them.
 *
 * · startDailyChallenge() — No daily mode yet. Alert placeholder.
 * · handleStop()          — No audio stream to stop (unlike Song Trivia).
 * · forceLifeline()       — No lifeline mechanic; the hint auto-fires in Easy mode.
 */
export function startDailyChallenge() { alert("Daily mode not available for Fast Math yet!"); }
export function handleStop()          { return; }
export function forceLifeline()       { return; }
